x-common: &common
  image: antonio3a/aaa-eureka-server:1.1.0
  networks:
    - antonio3a-bridge
  restart: always
  deploy:
    resources:
      limits:
        memory: 1G

x-common-env: &common-env
  EUREKA_ENVIRONMENT: development
  EUREKA_CLIENT_FETCH-REGISTRY: true
  EUREKA_CLIENT_REGISTER-WITH-EUREKA: true

services:
  antonio3a-eureka-1:
    <<: *common
    container_name: antonio3a-eureka-1
    hostname: eureka1.antonio3a.aaa
    environment:
      <<: *common-env
      SERVER_PORT: 8761
      eureka.client.service-url.defaultZone: http://eureka2.antonio3a.aaa:8762/eureka/, http://eureka3.antonio3a.aaa:8763/eureka/
    ports:
      - "8761:8761"
    healthcheck:
      test: "curl --fail --silent http://localhost:8761/actuator/health/readinessState | grep UP || exit 1"
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  antonio3a-eureka-2:
    <<: *common
    container_name: antonio3a-eureka-2
    hostname: eureka2.antonio3a.aaa
    environment:
      <<: *common-env
      SERVER_PORT: 8762
      eureka.client.service-url.defaultZone: http://eureka1.antonio3a.aaa:8761/eureka/, http://eureka3.antonio3a.aaa:8763/eureka/
    ports:
      - "8762:8762"
    healthcheck:
      test: "curl --fail --silent http://localhost:8762/actuator/health/readinessState | grep UP || exit 1"
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  antonio3a-eureka-3:
    <<: *common
    container_name: antonio3a-eureka-3
    hostname: eureka3.antonio3a.aaa
    environment:
      <<: *common-env
      SERVER_PORT: 8763
      eureka.client.service-url.defaultZone: http://eureka1.antonio3a.aaa:8761/eureka/, http://eureka2.antonio3a.aaa:8762/eureka/
    ports:
      - "8763:8763"
    healthcheck:
      test: "curl --fail --silent http://localhost:8763/actuator/health/readinessState | grep UP || exit 1"
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  antonio3a-bridge:
    external: true
