server:
  port: 8761

spring:
  application:
    name: antonio3a-eureka-server

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    instance-id: ${spring.application.name}:${random.long(100000,999999)}

management:
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    git:
      mode: full

  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    health:
      show-details: always

info:
  app:
    name: ${spring.application.name}
    description: ${spring.application.name} description
    version: ${project.version}
