server:
  port: 8761

spring:
  application:
    name: antonio3a-eureka-server
    version: 1.1.0

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

management:
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: ["health", "info", "metrics", "prometheus"]
    access:
      default: read_only
  endpoint:
    health:
      show-details: always
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: ${spring.application.name} description
    version: ${spring.application.version}
